### ISSUE TITLE
Cors issues

### ISSUE THREAD

**Issue by rakesanug** [cashfree/cordova-plugin-cashfree#10]
I have issues getting token 

**Sample code:**

  const tokenAPI = "https://test.cashfree.com/api/v2/cftoken/order";
    const appId = "appid";
    const secret = "secretId";
    let  headers = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PATCH, PUT, DELETE, OPTIONS",
      "x-client-secret": secret,
      "x-client-id": appId,
    }

    this.http.post(tokenAPI, data, { headers })

Screen shot
![image](https://user-images.githubusercontent.com/19207023/90006617-dab9f500-dcb6-11ea-9172-07c929b4fbdd.png)

**Comment by rajnandan1** [comment]
Have to make this using your backend server

**Comment by rakesanug** [comment]
But client side how to do?
