### ISSUE TITLE
Error: ReferenceError: reject is not defined

### ISSUE THREAD

**Issue by SnehaKotawade** [cashfree/cordova-plugin-cashfree#11]
While working with your example. I am getting Error: ReferenceError: reject is not defined.
I have followed all the steps as mention in document but getting error in  
Cashfree.checkout(skdInput).then(function (txResponse) {
          console.log(txResponse);
        }, function (response) {
          console.log('err', response)
        });

Please can you help me for the same. 
Thanks

**Comment by madhab-miraki** [comment]
Hi,
Please update the cashfree.js file of the plugin folder **www** folder to the attached code.
Then it will work fine.
[cashfree.txt](https://github.com/cashfree/cordova-plugin-cashfree/files/5079780/cashfree.txt)

**Comment by rakesanug** [comment]
Your sdk input is wrong. I was also facing same error. i corrected my sdk input now its working fine.

**Comment by kshirish** [comment]
@SnehaKotawade @madhab-miraki Should work now ... repo has been updated.

**Comment by manisundar186** [comment]
Hello kshirish..
I tried your repository but I'm facing an error that 'Corodova is not defined'. Am I need to include any js file in my index.html
